name: Build Project

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build sources jar
        run: ./gradlew sourcesJar

      - name: Build javadoc jar
        run: ./gradlew javadocJar

      - name: Build jars
        run: ./gradlew build
        
      - name: Upload pb-client
        uses: actions/upload-artifact@v3
        with:
          name: pb-client
          path: ./pb-client/build/libs

      - name: Upload pb-api
        uses: actions/upload-artifact@v3
        with:
          name: pb-api
          path: ./pb-api/build/libs
          
      - name: Upload pb-server
        uses: actions/upload-artifact@v3
        with:
          name: pb-server
          path: ./pb-server/build/libs

      - name: Remove *-sources.jar
        run: rm ./pb-client/libs/*-sources.jar || true
      - uses: "0xDylan/action-auto-releases-n20@v1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            ./pb-client/libs/*.jar
        
